
spring:
  application:
    name: eureka-server

#端口号
server:
  port: 8761

#eureka配置信息
eureka:
  #Eureka实例名，集群中根据这里相互识别
  instance:
    hostname: eureka

  #server:
    #自我保护机制 默认true。 开发时，可以设置为false.
    #enable-self-preservation: false

  client:
    ## 默认情况下,该服务注册中心也会将自己作为客户端来尝试向注册中心注册它自己,因此需要禁用它的客户端注册行为
    # 不向注册中心注册自己 false; 如果是集群 则配置为true
    register-with-eureka: false
    # 不需要从注册中心检索服务 false; 如果是集群 则配置为true
    fetch-registry: false
    #ָ注册中心地址
    serviceUrl.defaultZone: http://localhost:8761/eureka/